global:
  scrape_interval: 4s

scrape_configs:
  - job_name: 'travelmemory-backend'
    static_configs:
      - targets: ['172.21.61.204:3001']
  - job_name: 'mongodb'
    static_configs:
      - targets: ['172.21.61.204:9216']